version: '3.4'

services:
  ibge.minimalapi:
    image: ${DOCKER_REGISTRY-}ibgeminimalapi
    build:
      context: .
      dockerfile: IBGE.MinimalAPI/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:  
      - ./SQLS/Schema.sql:/tmp/Schema.sql
      - ./SQLS/Data.sql:/tmp/Data.sql
      - ./SQLS/DataFixes/2021-03-14-06-31_corrige_sigla_estado_roraima.sql:/tmp/DataFixes/2021-03-14-06-31_corrige_sigla_estado_roraima.sql
      - ./SQLS/init.sh:/tmp/init.sh